name: CI/CD for Frontend and Backend Docker Images

on:
  push:
    branches:
      - main
    paths:
      - "central-systems/frontend/client**" # Triggers for changes in cms frontend (Next.js)
      - "central-systems/backend/server**" # Triggers for changes in cms backend (Express.js)
      - "data-layer-microservice*/server**" # Triggers for changes in cms frontend (Next.js)
      - "kpi/backend/**" # Triggers for changes in cms backend (Express.js)

  pull_request:
    branches:
      - main
    paths:
      - "central-systems/frontend/client**" # Triggers for changes in cms frontend (Next.js)
      - "central-systems/backend/server**" # Triggers for changes in cms backend (Express.js)
      - "data-layer-microservice/server**" # Triggers for changes in cms frontend (Next.js)
      - "kpi/backend/**" # Triggers for changes in cms backend (Express.js)

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Frontend (Next.js) Build and Push for central-systems
      - name: Build and push frontend for central systems
        working-directory: ./central-systems/frontend/client
        run: |
          docker build -t cdevsit/cms-frontend:${GITHUB_SHA} .
          docker push cdevsit/cms-frontend:${GITHUB_SHA}

      # Backend (Express.js) Build and Push for central-systems
      - name: Build and push backend for central-systems
        working-directory: ./central-systems/backend/server
        run: |
          docker build -t cdevsit/cms-backend:${GITHUB_SHA} .
          docker push cdevsit/cms-backend:${GITHUB_SHA}

      # Backend (Express.js) Build and Push for kpi
      - name: Build and push backend for kpi
        working-directory: ./kpi/backend
        run: |
          docker build -t cdevsit/kpi-backend:${GITHUB_SHA} .
          docker push cdevsit/kpi-backend:${GITHUB_SHA}

      # Backend (Express.js) Build and Push for data-layer-microservice
      - name: Build and push backend for data-layer-microservice
        working-directory: ./data-layer-microservice/server
        run: |
          docker build -t cdevsit/cms-data-layer-backend:${GITHUB_SHA} .
          docker push cdevsit/cms-data-layer-backend:${GITHUB_SHA}
